############################################################################
# Contest 2026 team 470 XiaoPai device service
############################################################################

include $(APPDIR)/Make.defs

ifeq ($(CONFIG_LVX_USE_DEMO_CONTEST2026_470_XIAOPAI),y)

PROGNAME  = xiaopai
PRIORITY  = 100
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_470_XIAOPAI)

MAINSRC = xiaopai_main.c

include $(APPDIR)/Application.mk

endif
